In [1]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D, BatchNormalization
from Darknet53_model import Darknet53_yolo
from Darknet53_model import Darknet53
from IPython.core.display import display, HTML

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"] = "12"
gpus = tf.config.experimental.list_physical_devices("GPU")
tf.config.experimental.set_memory_growth(gpus[0], True)
display(HTML("<style>.container { width:98% !important;}</style>"))

In [3]:
Darknet_model = Darknet53()

In [4]:
Darknet_model.load_weights("weights/mul_weights.h5")

In [4]:
x_model = tf.keras.Model([Darknet_model.get_layer("Input_stage").input], 
                         [Darknet_model.get_layer("tf_op_layer_add_10").output,
                          Darknet_model.get_layer("tf_op_layer_add_18").output,
                          Darknet_model.get_layer("tf_op_layer_add_22").output])

In [5]:
x_model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    (None, 256, 256, 32) 864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali (None, 256, 256, 32) 128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak (None, 256, 256, 32) 0           stage0_layer_1_BN[0][0]          
____________________________________________________________________________________________

In [6]:
x_model.save_weights("aaa.h5")

In [6]:
new_model = Darknet53_yolo()

In [7]:
new_model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage_yolo (InputLayer)   [(None, 416, 416, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    (None, 416, 416, 32) 864         Input_stage_yolo[0][0]           
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali (None, 416, 416, 32) 128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak (None, 416, 416, 32) 0           stage0_layer_1_BN[0][0]          
____________________________________________________________________________________________

In [8]:
new_model.load_weights("aaa.h5")

In [14]:
Darknet_model.variables[92]

<tf.Variable 'stage3_layer_19_BN/beta:0' shape=(128,) dtype=float32, numpy=
array([-0.02864536, -0.02453053, -0.03887871, -0.04459788, -0.00643005,
       -0.03058669, -0.0205365 , -0.03102195, -0.03669186, -0.02222957,
       -0.02426526, -0.04911354, -0.00513093, -0.02291185, -0.02909859,
       -0.02205286, -0.03128448, -0.01109572, -0.03544669, -0.03767386,
       -0.01573831, -0.01931139, -0.02007987, -0.02373229, -0.02174238,
       -0.02224458, -0.02748846, -0.0433481 , -0.02167094, -0.03450674,
       -0.01563989, -0.00756992, -0.03434463, -0.01278008, -0.04627007,
       -0.02541011, -0.02699811,  0.00207576, -0.02050653, -0.03380077,
       -0.03074756, -0.02464641, -0.00396209, -0.02336948, -0.02863663,
       -0.0458127 ,  0.00202156, -0.0065769 , -0.03165362, -0.0390454 ,
       -0.02140011, -0.02742879, -0.02870968, -0.02889819, -0.02992249,
       -0.02336728, -0.03381719, -0.00658961, -0.00186339, -0.04469616,
       -0.01122078, -0.03743163, -0.03137597, -0.0211627 , -

In [15]:
new_model.variables[92]

<tf.Variable 'stage3_layer_19_BN_1/beta:0' shape=(128,) dtype=float32, numpy=
array([-0.02864536, -0.02453053, -0.03887871, -0.04459788, -0.00643005,
       -0.03058669, -0.0205365 , -0.03102195, -0.03669186, -0.02222957,
       -0.02426526, -0.04911354, -0.00513093, -0.02291185, -0.02909859,
       -0.02205286, -0.03128448, -0.01109572, -0.03544669, -0.03767386,
       -0.01573831, -0.01931139, -0.02007987, -0.02373229, -0.02174238,
       -0.02224458, -0.02748846, -0.0433481 , -0.02167094, -0.03450674,
       -0.01563989, -0.00756992, -0.03434463, -0.01278008, -0.04627007,
       -0.02541011, -0.02699811,  0.00207576, -0.02050653, -0.03380077,
       -0.03074756, -0.02464641, -0.00396209, -0.02336948, -0.02863663,
       -0.0458127 ,  0.00202156, -0.0065769 , -0.03165362, -0.0390454 ,
       -0.02140011, -0.02742879, -0.02870968, -0.02889819, -0.02992249,
       -0.02336728, -0.03381719, -0.00658961, -0.00186339, -0.04469616,
       -0.01122078, -0.03743163, -0.03137597, -0.0211627 ,

In [6]:
x_model = tf.keras.Model([Darknet_model.get_layer("Input_stage").input], 
                         [Darknet_model.get_layer("tf_op_layer_add_10").output,
                          Darknet_model.get_layer("tf_op_layer_add_18").output,
                          Darknet_model.get_layer("tf_op_layer_add_22").output])

In [7]:
x_model.save_weights("aaa.h5")

In [18]:
Darknet_model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    (None, 256, 256, 32) 864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali (None, 256, 256, 32) 128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak (None, 256, 256, 32) 0           stage0_layer_1_BN[0][0]          
______________________________________________________________________________________________

In [5]:
Darknet_model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    (None, 256, 256, 32) 864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali (None, 256, 256, 32) 128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak (None, 256, 256, 32) 0           stage0_layer_1_BN[0][0]          
______________________________________________________________________________________________

In [6]:
new_model = Darknet53_yolo()

In [11]:
Darknet_model.variables[0].name

'stage0_layer_1_Conv/kernel:0'

In [12]:
new_model.variables[0].name

'stage0_layer_1_Conv_1/kernel:0'

In [17]:
for i in range(len(new_model.variables)):
    print(Darknet_model.variables[i].name)
    print(new_model.variables[i].name)
    print("-"*30)

stage0_layer_1_Conv/kernel:0
stage0_layer_1_Conv_1/kernel:0
------------------------------
stage0_layer_1_BN/gamma:0
stage0_layer_1_BN_1/gamma:0
------------------------------
stage0_layer_1_BN/beta:0
stage0_layer_1_BN_1/beta:0
------------------------------
stage0_layer_1_BN/moving_mean:0
stage0_layer_1_BN_1/moving_mean:0
------------------------------
stage0_layer_1_BN/moving_variance:0
stage0_layer_1_BN_1/moving_variance:0
------------------------------
stage0_layer_2_Conv/kernel:0
stage0_layer_2_Conv_1/kernel:0
------------------------------
stage0_layer_2_BN/gamma:0
stage0_layer_2_BN_1/gamma:0
------------------------------
stage0_layer_2_BN/beta:0
stage0_layer_2_BN_1/beta:0
------------------------------
stage0_layer_2_BN/moving_mean:0
stage0_layer_2_BN_1/moving_mean:0
------------------------------
stage0_layer_2_BN/moving_variance:0
stage0_layer_2_BN_1/moving_variance:0
------------------------------
stage1_layer_3_Conv/kernel:0
stage1_layer_3_Conv_1/kernel:0
------------------

stage3_layer_23_BN/beta:0
stage3_layer_23_BN_1/beta:0
------------------------------
stage3_layer_23_BN/moving_mean:0
stage3_layer_23_BN_1/moving_mean:0
------------------------------
stage3_layer_23_BN/moving_variance:0
stage3_layer_23_BN_1/moving_variance:0
------------------------------
stage3_layer_24_Conv/kernel:0
stage3_layer_24_Conv_1/kernel:0
------------------------------
stage3_layer_24_BN/gamma:0
stage3_layer_24_BN_1/gamma:0
------------------------------
stage3_layer_24_BN/beta:0
stage3_layer_24_BN_1/beta:0
------------------------------
stage3_layer_24_BN/moving_mean:0
stage3_layer_24_BN_1/moving_mean:0
------------------------------
stage3_layer_24_BN/moving_variance:0
stage3_layer_24_BN_1/moving_variance:0
------------------------------
stage3_layer_25_Conv/kernel:0
stage3_layer_25_Conv_1/kernel:0
------------------------------
stage3_layer_25_BN/gamma:0
stage3_layer_25_BN_1/gamma:0
------------------------------
stage3_layer_25_BN/beta:0
stage3_layer_25_BN_1/beta:0
----

stage5_layer_47_BN/moving_mean:0
stage5_layer_47_BN_1/moving_mean:0
------------------------------
stage5_layer_47_BN/moving_variance:0
stage5_layer_47_BN_1/moving_variance:0
------------------------------
stage5_layer_48_Conv/kernel:0
stage5_layer_48_Conv_1/kernel:0
------------------------------
stage5_layer_48_BN/gamma:0
stage5_layer_48_BN_1/gamma:0
------------------------------
stage5_layer_48_BN/beta:0
stage5_layer_48_BN_1/beta:0
------------------------------
stage5_layer_48_BN/moving_mean:0
stage5_layer_48_BN_1/moving_mean:0
------------------------------
stage5_layer_48_BN/moving_variance:0
stage5_layer_48_BN_1/moving_variance:0
------------------------------
stage5_layer_49_Conv/kernel:0
stage5_layer_49_Conv_1/kernel:0
------------------------------
stage5_layer_49_BN/gamma:0
stage5_layer_49_BN_1/gamma:0
------------------------------
stage5_layer_49_BN/beta:0
stage5_layer_49_BN_1/beta:0
------------------------------
stage5_layer_49_BN/moving_mean:0
stage5_layer_49_BN_1/movi

In [16]:
new_model.variables

[<tf.Variable 'stage0_layer_1_Conv_1/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
 array([[[[-4.63446304e-02,  2.00173259e-02,  6.11347854e-02,
           -2.84754336e-02, -6.58634305e-03,  1.06991068e-01,
           -8.57896283e-02, -3.84588540e-03, -1.30199969e-01,
            3.57761979e-02,  6.40584528e-02, -1.19257450e-01,
            3.59780788e-02, -2.92732418e-02, -7.35901371e-02,
           -9.79602337e-03, -5.87712899e-02,  5.39682657e-02,
            3.82884294e-02,  1.16435632e-01,  2.42117494e-02,
            1.04285926e-01, -8.91116410e-02,  1.22328922e-01,
            3.63174230e-02, -1.31686032e-02, -1.65957808e-02,
           -9.34067369e-03, -1.78586021e-02, -6.90066218e-02,
           -1.43879950e-02,  1.09891668e-01],
          [ 4.17887121e-02, -5.92829660e-02,  1.23811468e-01,
            1.00630671e-02,  8.33971798e-03, -1.28884241e-01,
            1.05939820e-01, -1.14686638e-01,  5.50368130e-02,
            1.36060759e-01,  1.35428920e-01, -5.28630242e-0

In [9]:
new_model.variables[0]

<tf.Variable 'stage0_layer_1_Conv_1/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[-4.63446304e-02,  2.00173259e-02,  6.11347854e-02,
          -2.84754336e-02, -6.58634305e-03,  1.06991068e-01,
          -8.57896283e-02, -3.84588540e-03, -1.30199969e-01,
           3.57761979e-02,  6.40584528e-02, -1.19257450e-01,
           3.59780788e-02, -2.92732418e-02, -7.35901371e-02,
          -9.79602337e-03, -5.87712899e-02,  5.39682657e-02,
           3.82884294e-02,  1.16435632e-01,  2.42117494e-02,
           1.04285926e-01, -8.91116410e-02,  1.22328922e-01,
           3.63174230e-02, -1.31686032e-02, -1.65957808e-02,
          -9.34067369e-03, -1.78586021e-02, -6.90066218e-02,
          -1.43879950e-02,  1.09891668e-01],
         [ 4.17887121e-02, -5.92829660e-02,  1.23811468e-01,
           1.00630671e-02,  8.33971798e-03, -1.28884241e-01,
           1.05939820e-01, -1.14686638e-01,  5.50368130e-02,
           1.36060759e-01,  1.35428920e-01, -5.28630242e-02,
           2.

In [17]:
new_model.variables[-2]

<tf.Variable 'stage6_layer_53_Dense_1/kernel:0' shape=(1024, 1000) dtype=float32, numpy=
array([[-0.03630134, -0.01162803, -0.05116494, ...,  0.02588985,
        -0.03786769, -0.01187661],
       [-0.02858033, -0.01904901, -0.01131418, ...,  0.0299395 ,
        -0.02206795, -0.00211777],
       [-0.00077664, -0.00328908, -0.02796634, ..., -0.03533021,
        -0.02749157,  0.00313972],
       ...,
       [-0.02392697, -0.05090456,  0.04285571, ...,  0.01229553,
         0.02898442, -0.01143136],
       [-0.04791695, -0.02877688,  0.02493436, ...,  0.04289332,
         0.01792594, -0.01221906],
       [ 0.02610662,  0.05349462,  0.0312543 , ...,  0.00264179,
         0.03305201, -0.05040549]], dtype=float32)>

In [14]:
for i in new_model.variables:
    print(i)
    break

<tf.Variable 'stage0_layer_1_Conv_1/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[-1.23818465e-01,  2.53749639e-02,  1.29313454e-01,
          -1.18396625e-01,  6.66808039e-02,  1.25730827e-01,
          -1.23869374e-01, -8.91501382e-02, -8.79219174e-03,
          -3.46422195e-03,  1.33674398e-01,  9.53228623e-02,
          -1.05612680e-01, -5.44252470e-02, -4.73105162e-02,
          -1.12960249e-01, -1.14511617e-01, -5.86602092e-03,
           1.04623601e-01, -7.51200169e-02,  1.32841423e-01,
          -6.37454614e-02, -1.19991101e-01, -1.11883961e-01,
          -6.20363802e-02,  6.30092472e-02, -9.95820463e-02,
           2.91477144e-02,  1.02863014e-01,  5.22257239e-02,
          -1.11783803e-01, -1.74778253e-02],
         [-9.53074694e-02,  9.16293859e-02, -4.01048437e-02,
          -3.02006006e-02, -6.88927695e-02, -8.40342045e-03,
           2.47829407e-02,  1.15208402e-01, -1.25904709e-01,
          -1.04050130e-01,  1.19533256e-01, -8.83695632e-02,
           1.

In [13]:
new_model.variables

[<tf.Variable 'stage0_layer_1_Conv_1/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
 array([[[[-1.23818465e-01,  2.53749639e-02,  1.29313454e-01,
           -1.18396625e-01,  6.66808039e-02,  1.25730827e-01,
           -1.23869374e-01, -8.91501382e-02, -8.79219174e-03,
           -3.46422195e-03,  1.33674398e-01,  9.53228623e-02,
           -1.05612680e-01, -5.44252470e-02, -4.73105162e-02,
           -1.12960249e-01, -1.14511617e-01, -5.86602092e-03,
            1.04623601e-01, -7.51200169e-02,  1.32841423e-01,
           -6.37454614e-02, -1.19991101e-01, -1.11883961e-01,
           -6.20363802e-02,  6.30092472e-02, -9.95820463e-02,
            2.91477144e-02,  1.02863014e-01,  5.22257239e-02,
           -1.11783803e-01, -1.74778253e-02],
          [-9.53074694e-02,  9.16293859e-02, -4.01048437e-02,
           -3.02006006e-02, -6.88927695e-02, -8.40342045e-03,
            2.47829407e-02,  1.15208402e-01, -1.25904709e-01,
           -1.04050130e-01,  1.19533256e-01, -8.83695632e-0

In [11]:
new_model.get_layer("stage0_layer_1_Conv")

[array([[[[-1.23818465e-01,  2.53749639e-02,  1.29313454e-01,
           -1.18396625e-01,  6.66808039e-02,  1.25730827e-01,
           -1.23869374e-01, -8.91501382e-02, -8.79219174e-03,
           -3.46422195e-03,  1.33674398e-01,  9.53228623e-02,
           -1.05612680e-01, -5.44252470e-02, -4.73105162e-02,
           -1.12960249e-01, -1.14511617e-01, -5.86602092e-03,
            1.04623601e-01, -7.51200169e-02,  1.32841423e-01,
           -6.37454614e-02, -1.19991101e-01, -1.11883961e-01,
           -6.20363802e-02,  6.30092472e-02, -9.95820463e-02,
            2.91477144e-02,  1.02863014e-01,  5.22257239e-02,
           -1.11783803e-01, -1.74778253e-02],
          [-9.53074694e-02,  9.16293859e-02, -4.01048437e-02,
           -3.02006006e-02, -6.88927695e-02, -8.40342045e-03,
            2.47829407e-02,  1.15208402e-01, -1.25904709e-01,
           -1.04050130e-01,  1.19533256e-01, -8.83695632e-02,
            1.81710720e-02, -9.69773233e-02,  2.62804329e-03,
           -5.33398762e-

In [52]:
inputs = tf.keras.layers.Input(shape=(416, 416, 3,))

In [56]:
x = Darknet_model.get_layer("stage0_layer_1_Conv")(inputs)

In [69]:
Darknet_model.input.shape

TensorShape([None, 256, 256, 3])

In [74]:
tf.TensorShape([None, 416, 416, 3])

TensorShape([None, 416, 416, 3])

In [75]:
Darknet_model.input.shape = tf.TensorShape([None, 416, 416, 3])

AttributeError: can't set attribute

In [66]:
model = tf.keras.Model(Darknet_model.input, [Darknet_model.get_layer("stage5_layer_51_Conv").output,
                                             Darknet_model.get_layer("stage5_layer_52_Conv").output])

In [63]:
model.summary()

Model: "model_24"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    (None, 256, 256, 32) 864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali (None, 256, 256, 32) 128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak (None, 256, 256, 32) 0           stage0_layer_1_BN[0][0]          
___________________________________________________________________________________________

In [ ]:
x_model = tf.keras.Model([Darknet_model.get_layer("Input_stage").input], 
                         [Darknet_model.get_layer("tf_op_layer_add_10").output,
                          Darknet_model.get_layer("tf_op_layer_add_18").output,
                          Darknet_model.get_layer("tf_op_layer_add_22").output])

In [35]:
x_model.summary()

Model: "model_9"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    multiple             864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali multiple             128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak multiple             0           stage0_layer_1_BN[0][0]          
____________________________________________________________________________________________

In [37]:
x_model = tf.keras.Model([Darknet_model.get_layer("Input_stage").input], 
                         [Darknet_model.get_layer("tf_op_layer_add_10").output,
                          Darknet_model.get_layer("tf_op_layer_add_18").output,
                          Darknet_model.get_layer("tf_op_layer_add_22").output])

In [38]:
x_model.summary()

Model: "model_12"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    multiple             864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali multiple             128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak multiple             0           stage0_layer_1_BN[0][0]          
___________________________________________________________________________________________

In [31]:
inputs = tf.keras.layers.Input(shape=(416, 416, 3,))

In [32]:
x = x_model(inputs)

In [36]:
aa = tf.keras.Model([inputs], [x_model.get_layer("tf_op_layer_add_10").output,
                               x_model.get_layer("tf_op_layer_add_18").output])

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("Input_stage:0", shape=(None, 256, 256, 3), dtype=float32) at layer "Input_stage". The following previous layers were accessed without issue: []

In [34]:
aa.summary()

Model: "model_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 416, 416, 3)]     0         
_________________________________________________________________
model_9 (Model)              multiple                  40620640  
Total params: 40,620,640
Trainable params: 40,584,928
Non-trainable params: 35,712
_________________________________________________________________


In [24]:
x_model.summary()

Model: "model_6"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_stage (InputLayer)        [(None, 256, 256, 3) 0                                            
__________________________________________________________________________________________________
stage0_layer_1_Conv (Conv2D)    multiple             864         Input_stage[0][0]                
__________________________________________________________________________________________________
stage0_layer_1_BN (BatchNormali multiple             128         stage0_layer_1_Conv[0][0]        
__________________________________________________________________________________________________
stage0_layer_1_Activation (Leak multiple             0           stage0_layer_1_BN[0][0]          
____________________________________________________________________________________________

In [12]:
inputs = tf.keras.layers.Input(shape=(416, 416, 3,))

In [19]:
x = Darknet_model(inputs)

In [20]:
x.summary()

AttributeError: 'Tensor' object has no attribute 'summary'

In [14]:
output = Darknet_model.get_layer("tf_op_layer_add_22").output

In [16]:
x_model = tf.keras.Model([])

In [17]:
x_model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 416, 416, 3)]     0         
_________________________________________________________________
model (Model)                (None, 1000)              41645640  
Total params: 41,645,640
Trainable params: 41,609,928
Non-trainable params: 35,712
_________________________________________________________________


In [ ]:
output1 = 

In [23]:
Darknet_model.get_layer("stage0_layer_1_Conv").input(tf.random.normal(32, 256, 256, 3))

NotFoundError: Could not find valid device for node.
Node:{{node RandomStandardNormal}}
All kernels registered for op RandomStandardNormal :
  device='XLA_GPU'; T in [DT_INT32, DT_INT64]; dtype in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU'; T in [DT_INT32, DT_INT64]; dtype in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='XLA_CPU_JIT'; T in [DT_INT32, DT_INT64]; dtype in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]
  device='CPU'; dtype in [DT_BFLOAT16]
  device='CPU'; dtype in [DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_INT32, DT_INT64]; dtype in [DT_FLOAT, DT_DOUBLE, DT_BFLOAT16, DT_HALF]
  device='GPU'; T in [DT_INT32]; dtype in [DT_DOUBLE]
  device='GPU'; T in [DT_INT32]; dtype in [DT_FLOAT]
  device='GPU'; T in [DT_INT32]; dtype in [DT_HALF]
 [Op:RandomStandardNormal]

In [19]:
inputs = tf.keras.layers.Input(shape=(416, 416, 3,))
x = Conv2D(32, (3, 3), padding="SAME")(inputs)
model = tf.keras.Model(inputs, x)

In [20]:
model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         [(None, 416, 416, 3)]     0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 416, 416, 32)      896       
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [ ]:
inputs = tf.keras.layers.Input(in)